apiVersion: v2
name: dkatalis-techvify-chart
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.0.1"
dependencies:
  - name: mongodb
    version: 11.1.1
    repository: "https://charts.bitnami.com/bitnami"
    condition: mongodb.enabled
    alias: mongodb
  - name: redis
    version: 16.2.1
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
    alias: redis
  - name: kafka
    repository: "https://charts.bitnami.com/bitnami"
    version: 16.2.9
    condition: kafka.enabled
    alias: kafka
