redis:
  enabled: true
  password: password123
  cluster:
    enabled: false
  master:
    disableCommands: []
kafka:
  enabled: true
  externalAccess:
    enabled: true
    service:
      type: LoadBalancer
      domain: localhost
      port: 9094
    autoDiscovery:
      enabled: true
  serviceAccount:
    create: true
  rbac:
    create: true
#Todo: update to their credential
mongodb:
  enabled: true
  externalAccess:
    enabled: true
    service:
      type: LoadBalancer
      domain: localhost
      port: 27017
  auth:
    rootPassword: password123
    databases: [test]
    usernames: [dukevu]
    passwords: [password123]